### ISSUE TITLE
Docker command in README fails

### ISSUE THREAD

**Issue by pbanavara** [aerospike/aerospike-server-enterprise.docker#3]
The current docker command in the README is failing

docker run -tid --name aerospike_ent1 -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 -v /opt/aerospike:/etc/aerospike/ -e "FEATURE_KEY_FILE=/etc/aerospike/features.conf" aerospike/aerospike-server-enterprise

Container does not start and `docker logs` reveals only this 

```
(base) pradeepbanavara@Pradeeps-MacBook-Pro ~ % docker logs 74436ed2e84d
link eth0 state up
link eth0 state up in 0
```

This was working a few days ago not sure what has happened.

**Comment by spkesan** [comment]
Hi @pbanavara ,

Don't try to mount any volume to `/etc/aerospike/` path inside the container. The default `aerospike.conf` file lies in `/etc/aerospike/aerospike.conf` by default. If you mount any volume to `/etc/aerospike/` path of the container, the pre-existing files will be hidden and won't be accessible. So in this case, aerospike didn't start probably due to unable to access aerospike.conf file.

Try this,

```
docker run -tid --name aerospike_ent1 -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 -v /opt/aerospike:/opt/etc/aerospike/ -e "FEATURE_KEY_FILE=/opt/etc/aerospike/features.conf" aerospike/aerospike-server-enterprise
```

I'll fix the example in README.
Thanks for reporting.

**Comment by spkesan** [comment]
Fixed in commit - [Minor fix - docker run example command](https://github.com/aerospike/aerospike-server-enterprise.docker/commit/d5d0e376ba2d7dfcfd961fe5f0bebdf1acb96bec)
